apiVersion: v1
kind: Pod
metadata:
  name: test-pod-v1
  labels:
    project: my_pod
spec:
  containers:
  - name: simply-byte-calculator
    image: simplebyte/simplybyte-calculator
    ports:
    - containerPort: 5000